on: [push]
env:
    user_name: "Chaminda"
    demo_name: "Variable Demo"
jobs:
 Variab111leUsageJob:
  runs-on: ubuntu-latest
  steps:
  - name: Using Workflow Variables
    run: echo Hello, $user_name!
